name: Build and Test Application

on:
  push:
    branches: [tpDockerCompose]
  pull_request:
    branches: [tpDockerCompose]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MongoDB image
        run: docker build -t dantr3b/mongo-blog:1.0.0 -f mongo/Dockerfile ./mongo

      - name: Build Python API image
        run: docker build -t dantr3b/python-api:1.0.0 -f api/Dockerfile ./api

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Scout Scan MongoDB
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: dantr3b/mongo-blog:1.0.0
          file: mongo/Dockerfile
          only-severities: critical,high
          exit-code: false

      - name: Docker Scout Scan Python API
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: dantr3b/python-api:1.0.0
          file: api/Dockerfile
          only-severities: critical,high
          exit-code: false

  docker_compose:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Stack
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        run: docker compose up -d
